--alter session set "_ORACLE_SCRIPT"=true;
DROP USER TQREACTOR CASCADE;
--alter session set "_ORACLE_SCRIPT"=false;
CREATE USER TQREACTOR IDENTIFIED BY tq;
GRANT DBA TO TQREACTOR;
GRANT EXECUTE ON DBMS_LOCK TO TQREACTOR;
GRANT EXECUTE ON DBMS_CQ_NOTIFICATION TO TQREACTOR;
GRANT CHANGE NOTIFICATION TO TQREACTOR;    
GRANT SELECT ON V_$TRANSACTION TO TQREACTOR;
