--alter session set "_ORACLE_SCRIPT"=true;
DROP USER TQREACTOR CASCADE;
--alter session set "_ORACLE_SCRIPT"=false;
CREATE USER TQREACTOR IDENTIFIED BY tq;
GRANT DBA TO TQREACTOR;
GRANT EXECUTE ON DBMS_LOCK TO TQREACTOR;
GRANT EXECUTE ON DBMS_CQ_NOTIFICATION TO TQREACTOR;
GRANT CHANGE NOTIFICATION TO TQREACTOR;    
GRANT SELECT ON V_$TRANSACTION TO TQREACTOR;
grant select on v_$mystat to TQREACTOR;
GRANT EXECUTE ON DBMS_ALERT TO TQREACTOR;



create user TQREACTOR identified by tq;
grant DBA to TQREACTOR;
grant all on UTL_TCP to TQREACTOR;
grant all on DBMS_TRANSACTION to TQREACTOR;
grant select on V_$TRANSACTION to TQREACTOR;
BEGIN
  DBMS_NETWORK_ACL_ADMIN.CREATE_ACL('netacl.xml', 'Allow usage to the UTL network packages', 'TQREACTOR', TRUE, 'connect');
  DBMS_NETWORK_ACL_ADMIN.ADD_PRIVILEGE('netacl.xml' ,'TQREACTOR', TRUE, 'resolve');
  DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL('netacl.xml','*');
  COMMIT;
END;
