--alter session set "_ORACLE_SCRIPT"=true;
DROP USER TQREACTOR CASCADE;
--alter session set "_ORACLE_SCRIPT"=false;
CREATE USER TQREACTOR IDENTIFIED BY tq;
GRANT DBA TO TQREACTOR;
GRANT EXECUTE ON DBMS_LOCK TO TQREACTOR;
GRANT EXECUTE ON DBMS_TRANSACTION to TQREACTOR;
GRANT SELECT ON V_$TRANSACTION TO TQREACTOR;
GRANT SELECT ON v_$MYSTAT to TQREACTOR;
GRANT SELECT ON v_$OSSTAT to TQREACTOR;
GRANT EXECUTE ON DBMS_ALERT TO TQREACTOR;
GRANT EXECUTE ON DBMS_APPLICATION_INFO TO TQREACTOR;

1. SYS Logging Package and Table
2. DDL  (minus tqstubs trigger)
3. TQ Package and Body
4. tqstubs trigger
5. TestData package and body
