#!/bin/bash
#export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_31
export JAVA_HOME=/usr/lib/jvm/jdk1.7.0_71
export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
export JPUB_LIBS=/home/nwhitehead/libs/java/oracle/jpub
export CLASSPATH=$JPUB_LIBS/ojdbc6.jar:$JPUB_LIBS/translator.jar:$JPUB_LIBS/runtime12.jar
export CLASS_DIR=/home/nwhitehead/hprojects/tqueue/src/main/java
export PACKAGE=tqueue.db.types
export TYPES=TQSTUB,TQSTUB_ARR,TQBATCH_ARR,TQBATCH,TQTRADE,TQTRADE_ARR,XROWIDS
export JURL=jdbc:oracle:thin:@//localhost:1521/XE
echo $CLASSPATH
#$JAVA_HOME/bin/java oracle.jpub.Doit -url=jdbc:oracle:thin:@//tporacle:1521/ORCL -user=tqreactor/tq -dir=. -numbertypes=objectjdbc -builtintypes=jdbc -usertypes=jdbc -package=tq -case=mixed -serializable=true -tostring=true -compile=true -sql=TQSTUB,TQSTUB_ARR
#$JAVA_HOME/bin/java oracle.jpub.Doit -url=jdbc:oracle:thin:@//tporacle:1521/ORCL -user=tqreactor/tq -dir=$CLASS_DIR -numbertypes=objectjdbc -builtintypes=jdbc -package=$PACKAGE -case=mixed -serializable=true -tostring=true -compile=true -sql=TQSTUB,TQSTUB_ARR
#$JAVA_HOME/bin/java oracle.jpub.Doit -url=jdbc:oracle:thin:@//tporacle:1521/ORCL -user=tqreactor/tq -dir=$CLASS_DIR -numbertypes=jdbc -builtintypes=jdbc -usertypes=jdbc -package=$PACKAGE -case=mixed -serializable=true -tostring=true -compile=true -sql=JTQSTUB,JTQSTUB_ARR
$JAVA_HOME/bin/java oracle.jpub.Doit -url=$JURL -user=tqreactor/tq -dir=$CLASS_DIR -numbertypes=jdbc -builtintypes=jdbc -package=$PACKAGE -case=mixed -serializable=true -tostring=true -compile=true -sql=$TYPES



###
# Example Call:
###
# e.g. c:\projects\jpub>jpub -user=ecs/ecs@orcl -dir=. -numbertypes=objectjdbc -builtintypes=jdbc -package=tq -case=mixed -serializable=true -tostring=true -compile=true -sql=TQSTUB,TQSTUB_ARR
# e.g. c:\projects\jpub>jpub -dir=. -numbertypes=objectjdbc -builtintypes=jdbc -package=tq -case=mixed -serializable=true -tostring=true -compile=true -sql=TQSTUB,TQSTUB_ARR
# -url=jdbc:oracle:oci:@
# jdbc:oracle:thin:@//[HOST][:PORT]/SERVICE
#  /home/nwhitehead/hprojects/tqueue/src/main/java/tqueue/db/types